# In .github/workflows/scrape_talks.yml

name: Scrape Talk Locations and Update Map

on:
  push:
    paths:
      - '_talks/**'
      - 'talkmap.ipynb'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_commit:
    runs-on: ubuntu-latest

    # Grant the workflow write permissions to push changes back to the repo
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        # Use the latest version of the checkout action
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        # Use the latest version of the setup-python action
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache Pip dependencies
        # This step saves your installed packages to speed up future runs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }} # Change if you have a requirements file
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas requests beautifulsoup4 geopy getorg

      - name: Execute Jupyter Notebook
        # This runs your talkmap.ipynb and creates/overwrites talkmap_out.ipynb
        run: |
          jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

      - name: Commit and push changes
        # This improved step only tries to commit if there are actual changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add all changes (including the new notebook output)
          git add talkmap_out.ipynb
          
          # Check if there are any changes to commit
          if ! git diff --staged --quiet; then
            # If there are changes, commit and push them
            git commit -m "Automated update of talk locations map"
            git push
          else
            # If there are no changes, just print a message
            echo "No changes to commit."
          fi
